name = "featherlite"
compatibility_date = "2024-04-30"

routes = [
  { pattern = "feather.minty.horse", custom_domain = true },
]

[vars]
# optional: environment variables

[[r2_buckets]]
binding = "FEATHERLITE_STATIC"
bucket_name = "featherlite-static"
