name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm ci

      - name: Download Pyodide
        run: npm run pyodide:download

      - name: Extract Pyodide
        run: npm run pyodide:extract

      - name: Build project
        run: npm run build

      - name: Upload files to R2
        run: |
          find dist -type f | while read filepath; do
            key=${filepath#dist/}
            echo "Uploading $filepath to $R2_BUCKET_NAME/$key"
            npx wrangler r2 object put "$R2_BUCKET_NAME/$key" --file "$filepath"
          done
        env:
          R2_BUCKET_NAME: featherlite-static
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy Worker
        run: |
          npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
